 steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA', '.']
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA']
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - '$TRIGGER_NAME'
   - '--image'
   - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--port'
   - '8080'
   - '--allow-unauthenticated'
   - '--set-env-vars'
   - 'PORT=$_PORT,DB_URL=$_DB_URL,DB_NAME=$_DB_NAME,DB_TAX_COLLECTION=$_DB_TAX_COLLECTION,DB_INVOICE_COLLECTION=$_DB_INVOICE_COLLECTION,DB_CLIENT_COLLECTION=$_DB_CLIENT_COLLECTION,DB_RIDER_COLLECTION=$_DB_RIDER_COLLECTION,TAX_RATE=$_TAX_RATE'
 images:
 - 'gcr.io/$PROJECT_ID/$TRIGGER_NAME:$COMMIT_SHA'
